postgres:
  image: timescale/timescaledb
  ports:
    - 5432:5432
  environment:
    POSTGRES_PASSWORD: postgres
    POSTGRES_USER: postgres
    PGDATA : /var/lib/postgresql/data/pgdata
    PGDATABASE: aerogear_mobile_metrics